//Author: Sameera Bammidi
//This is a generated class
package org.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SurveyWebService", targetNamespace = "http://webservice.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SurveyWebService {


    /**
     * 
     * @param firstName
     * @param lastName
     * @param city
     * @param state
     * @return
     *     returns java.util.List<org.webservice.StudentData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listStudent", targetNamespace = "http://webservice.org/", className = "org.webservice.ListStudent")
    @ResponseWrapper(localName = "listStudentResponse", targetNamespace = "http://webservice.org/", className = "org.webservice.ListStudentResponse")
    @Action(input = "http://webservice.org/SurveyWebService/listStudentRequest", output = "http://webservice.org/SurveyWebService/listStudentResponse")
    public List<StudentData> listStudent(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "state", targetNamespace = "")
        String state);

}
